import type { GameParameters } from "./types";

export const PRESET_PARAMETERS: Record<"easy" | "medium" | "hard", GameParameters> = {
  easy: {
    startingCapital: 50000,
    periodDurationMinutes: 15,
    marketAnalysisCost: 2000,
    negativeCashInterestRate: 0.05,
    initialMarketSaturationFactor: 0.8,
    priceElasticityFactor: 0.8,
    demandReferencePrice: 100,
    minPriceElasticityDemandMultiplier: 0.5,
    inventoryCostPerUnit: 5,
    rndBenefitThreshold: 10000,
    rndVariableCostReduction: 0.1,
    machineDegradationRate: 0.05,
    isRndEnabled: true,
    marketingEffectivenessFactor: 1.2,
    allowMachinePurchaseNextPeriod: false,
    demandBoostNextPeriod: false,
    freeMarketAnalysisNextPeriod: false,
    noInventoryCostsNextPeriod: false,
    customEventNextPeriod: "",
    machineDepreciationEnabled: false,
    machineDepreciationRate: 0.1,
  },
  medium: {
    startingCapital: 40000,
    periodDurationMinutes: 12,
    marketAnalysisCost: 3000,
    negativeCashInterestRate: 0.08,
    initialMarketSaturationFactor: 0.7,
    priceElasticityFactor: 1.0,
    demandReferencePrice: 100,
    minPriceElasticityDemandMultiplier: 0.4,
    inventoryCostPerUnit: 8,
    rndBenefitThreshold: 15000,
    rndVariableCostReduction: 0.12,
    machineDegradationRate: 0.08,
    isRndEnabled: true,
    marketingEffectivenessFactor: 1.0,
    allowMachinePurchaseNextPeriod: false,
    demandBoostNextPeriod: false,
    freeMarketAnalysisNextPeriod: false,
    noInventoryCostsNextPeriod: false,
    customEventNextPeriod: "",
    machineDepreciationEnabled: false,
    machineDepreciationRate: 0.1,
  },
  hard: {
    startingCapital: 30000,
    periodDurationMinutes: 10,
    marketAnalysisCost: 5000,
    negativeCashInterestRate: 0.12,
    initialMarketSaturationFactor: 0.6,
    priceElasticityFactor: 1.2,
    demandReferencePrice: 100,
    minPriceElasticityDemandMultiplier: 0.3,
    inventoryCostPerUnit: 12,
    rndBenefitThreshold: 20000,
    rndVariableCostReduction: 0.15,
    machineDegradationRate: 0.1,
    isRndEnabled: true,
    marketingEffectivenessFactor: 0.8,
    allowMachinePurchaseNextPeriod: false,
    demandBoostNextPeriod: false,
    freeMarketAnalysisNextPeriod: false,
    noInventoryCostsNextPeriod: false,
    customEventNextPeriod: "",
    machineDepreciationEnabled: false,
    machineDepreciationRate: 0.1,
  },
};
