import type { GameParameters } from "./types";

export const PRESET_PARAMETERS: Record<"easy" | "medium" | "hard", GameParameters> = {
  easy: {
    startingCapital: 50000,
    periodDurationMinutes: 15,
    marketAnalysisCost: 2000,
    negativeCashInterestRate: 0.05,
    initialMarketSaturationFactor: 0.8,
    priceElasticityFactor: 0.8,
    demandReferencePrice: 100,
    inventoryCostPerUnit: 5,
    rndBenefitThreshold: 2000,
    rndVariableCostReduction: 0.2,
    marketingEffectivenessFactor: 0.3,
    allowMachinePurchaseNextPeriod: false,
    demandBoostNextPeriod: false,
    freeMarketAnalysisNextPeriod: false,
    noInventoryCostsNextPeriod: false,
    customEventNextPeriod: "",
    machineDepreciationEnabled: false,
    machineDepreciationRate: 0.1,
  },
  medium: {
    startingCapital: 40000,
    periodDurationMinutes: 12,
    marketAnalysisCost: 3000,
    negativeCashInterestRate: 0.08,
    initialMarketSaturationFactor: 0.7,
    priceElasticityFactor: 1.0,
    demandReferencePrice: 100,
    inventoryCostPerUnit: 8,
    rndBenefitThreshold: 3000,
    rndVariableCostReduction: 0.22,
    marketingEffectivenessFactor: 0.25,
    allowMachinePurchaseNextPeriod: false,
    demandBoostNextPeriod: false,
    freeMarketAnalysisNextPeriod: false,
    noInventoryCostsNextPeriod: false,
    customEventNextPeriod: "",
    machineDepreciationEnabled: false,
    machineDepreciationRate: 0.1,
  },
  hard: {
    startingCapital: 30000,
    periodDurationMinutes: 10,
    marketAnalysisCost: 5000,
    negativeCashInterestRate: 0.12,
    initialMarketSaturationFactor: 0.6,
    priceElasticityFactor: 1.2,
    demandReferencePrice: 100,
    inventoryCostPerUnit: 12,
    rndBenefitThreshold: 4500,
    rndVariableCostReduction: 0.25,
    marketingEffectivenessFactor: 0.2,
    allowMachinePurchaseNextPeriod: false,
    demandBoostNextPeriod: false,
    freeMarketAnalysisNextPeriod: false,
    noInventoryCostsNextPeriod: false,
    customEventNextPeriod: "",
    machineDepreciationEnabled: false,
    machineDepreciationRate: 0.1,
  },
};
